[package]
name = "stat_finder"
version = "0.1.0"
authors = ["PotatoPresident <potatoboy9999@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
